apiVersion: v1
kind: Service
metadata:
  name: {{ template "{{py-api-template}}.fullname" . }}-{{ .Values.environment.stage }}
  labels:
    app: {{ template "{{py-api-template}}.name" . }}
    chart: {{ template "{{py-api-template}}.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: {{ template "{{py-api-template}}.name" . }}
    release: {{ .Release.Name }}